### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by ThanichaMongkorn** [ThanichaMongkorn/project-OOP---Group19#12]

**Comment by Hewkai** [comment]
https://www.figma.com/file/uF3udfsvtY4L3wAuxCobxx/Untitled?type=design&node-id=0%3A1&mode=design&t=QepoEQRkJlOFafrr-1

This is a first prototype for UI, maybe change in the future.

**Comment by Hewkai** [comment]
> https://www.figma.com/file/uF3udfsvtY4L3wAuxCobxx/Untitled?type=design&node-id=0%3A1&mode=design&t=QepoEQRkJlOFafrr-1
> 
> This is a first prototype for UI, maybe change in the future.

P.S. Book Icon under Player's information is contruction plan.

**Comment by Hewkai** [comment]
I sketch on paint before working on Figma.
![sketch](https://github.com/ThanichaMongkorn/project-OOP---Group19/assets/110963185/92af6ffd-cacc-401e-8f71-1861789cd5b4)
