### ISSUE TITLE
Design overview document for game state and user interface

### ISSUE THREAD

**Issue by ThanichaMongkorn** [ThanichaMongkorn/project-OOP---Group19#8]
This includes the outline of the display (view and controller) and your class hierarchy (model).
Your design will be given feedback, so you can address flaws before you submit your code.

**Comment by JWJY** [comment]
[Uploading design overview.pdf…]()

**Comment by JWJY** [comment]
[design overview.pdf](https://github.com/ThanichaMongkorn/project-OOP---Group19/files/14193621/design.overview.pdf)
